pipeline {
    agent any
    stages { 
        stage('Checkout') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "${WORKSPACE}"
            }
        }
    }
}