pipeline {
    agent any
    stages { 
        stage 'Checkout'
            node {
                deleteDir()
                checkout scm
            }

        stage 'Build'
            Wks = "${WORKSPACE}"
            node {
                echo Wks
            }
    }
}