pipeline {
    agent any
    stages { 
        node {
            stage('Build') {
                steps {
                    evaluate(new File("${WORKSPACE}/pipeline/pipeline1.groovy"))
                }
            }
        }
    }
}